sudo: false

language: go

env:
  - GO111MODULE=on

go:
  - 1.15.3

git:
  depth: 1

notifications:
  email: false

script:
  - golangci-lint run # run a bunch of code checkers/linters in parallel
  - go test -v -race ./... # Run all the tests with the race detector enabled
